spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE
    username: sa
    password: sa

    hikari:
      connectionTimeout: 1000
      maximumPoolSize: 200
      minimumIdle: 1
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
      timezone:
        default_storage: NORMALIZE_UTC

    properties:
      hibernate:
        hbm2ddl:
          import_files: nomenclature-data.sql,demo-data.sql # TODO: Remove demo-data in PROD env.
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always

  error:
    include-stacktrace: never
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json, text/csv
    min-response-size: 1024
  servlet:
    session:
      timeout: 30m

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui

logging:
  level:
    org.springframework: ERROR
    org.springframework.security: INFO
    com.example: INFO

jobs:
  deleteOldTransactions:
    maxAgeInHours: 1
    cronTrigger: 0 0 * * * ?
