spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE
    username: sa
    password: sa

#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/empay
#    username: empay
#    password: secret123


  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        hbm2ddl:
          import_files: nomenclature-data.sql,demo-data.sql

logging:
  level:
    org.springframework: ERROR
    org.springframework.security: INFO
    #    org.hibernate.SQL: DEBUG
    #    org.hibernate.orm.jdbc.bind: TRACE
    com.example: INFO
